# Generated by Django 3.0.8 on 2020-12-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_vechile_vechiletype_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='harga_beli',
            field=models.DecimalField(blank='True', decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='jumlah_seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
