# Generated by Django 3.0.8 on 2020-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='harga_beli',
            field=models.DecimalField(blank='True', decimal_places=0, max_digits=10, null=True),
        ),
    ]
