# Generated by Django 3.0.8 on 2020-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_vechile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechile',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
