# Generated by Django 3.0.8 on 2020-11-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vechile_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='photo',
            field=models.ImageField(null=True, upload_to='store/images/'),
        ),
    ]
