# Generated by Django 3.0.8 on 2020-11-21 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201121_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='IDJenis',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='store.VechileType'),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='harga_beli',
            field=models.PositiveIntegerField(blank='True'),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='photo',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='scan_faktur_beli',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='tanggal_pembelian',
            field=models.DateField(blank='True'),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='tanggal_stnk',
            field=models.DateField(blank='True'),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='vendor_id',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='store.Vendor'),
        ),
    ]
