# Generated by Django 3.0.8 on 2020-11-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201121_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechiletype',
            name='merek',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='status_stnk',
            field=models.CharField(choices=[('hidup', 'Hidup'), ('mati', 'Mati')], max_length=10),
        ),
    ]
