# Generated by Django 3.0.8 on 2020-11-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201122_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechiletype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vechiletype',
            name='IDJenis',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
