# Generated by Django 3.0.8 on 2020-11-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201122_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vechile',
            name='IDJenis',
        ),
        migrations.DeleteModel(
            name='VechileType',
        ),
    ]
