# Generated by Django 3.0.8 on 2020-11-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201123_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechileType',
            fields=[
                ('IDJenis', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jenis', models.CharField(choices=[('big', 'Big'), ('medium', 'Medium'), ('elf', 'Elf'), ('hiace', 'Hiace'), ('sprinter', 'Sprinter')], max_length=10)),
                ('jumlah_seat', models.CharField(max_length=20, null=True)),
                ('merek', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
