# Generated by Django 3.0.8 on 2020-11-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_vechile_idjenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='harga_beli',
            field=models.PositiveIntegerField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='status_stnk',
            field=models.CharField(blank='True', choices=[('hidup', 'Hidup'), ('mati', 'Mati')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='tanggal_pembelian',
            field=models.DateField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='tanggal_stnk',
            field=models.DateField(blank='True', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=10),
        ),
    ]
