# Generated by Django 3.0.8 on 2020-12-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20201129_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechile',
            name='expires_today',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='IDJenis',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.VechileType'),
        ),
        migrations.AlterField(
            model_name='vechile',
            name='no_polisi',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
