# Generated by Django 3.0.8 on 2021-02-13 14:20

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_auto_20201221_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('idbooking', models.CharField(default=booking.models.random_string, max_length=10, primary_key=True, serialize=False)),
                ('start', models.DateField(blank='True', null=True)),
                ('end', models.DateField(blank='True', null=True)),
                ('harga_jual', models.DecimalField(blank='True', decimal_places=0, max_digits=10, null=True)),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('uang_jalan', models.DecimalField(blank='True', decimal_places=0, max_digits=10, null=True)),
                ('parkir_bensin', models.DecimalField(blank='True', decimal_places=0, max_digits=10, null=True)),
                ('note', models.CharField(blank='True', max_length=15, null=True)),
                ('title', models.CharField(blank=True, max_length=15)),
                ('status_pembayaran', models.CharField(blank='True', choices=[('pending', 'Pending'), ('dp', 'Down Payment'), ('full', 'Full Payment')], max_length=15, null=True)),
                ('resourceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Vechile')),
            ],
        ),
    ]
