# Generated by Django 3.0.8 on 2021-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=35)),
                ('alamat_pelanggan', models.CharField(blank='True', max_length=220)),
                ('tipe', models.CharField(blank='True', choices=[('agen', 'Agen'), ('perorangan', 'Perorangan'), ('perusahaan', 'Perusahaan'), ('instansi', 'Instansi')], max_length=10)),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='nama_pelanggan',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Customer'),
        ),
    ]
