# Generated by Django 3.0.8 on 2021-02-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210215_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status_pembayaran',
        ),
        migrations.AddField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(blank='True', choices=[('blue', 'Pending'), ('yellow', 'Down Payment'), ('green', 'Full Payment')], max_length=15, null=True),
        ),
    ]
