# Generated by Django 3.0.8 on 2021-02-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210215_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(choices=[('blue', 'Pending'), ('yellow', 'Down Payment'), ('green', 'Full Payment')], max_length=15, null=True),
        ),
    ]
