# Generated by Django 3.0.8 on 2021-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210217_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(blank=True, choices=[('#17a2b8', 'Pending'), ('#ffc107', 'Down Payment'), ('#62bfa8', 'Full Payment')], default='blue', max_length=15),
        ),
    ]
