# Generated by Django 3.0.8 on 2021-02-19 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210218_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='backgroundColor',
            field=models.CharField(blank=True, choices=[('#17a2b8', 'Pending'), ('#ffc107', 'Down Payment'), ('#28a745', 'Full Payment')], default='#17a2b8', max_length=15),
        ),
    ]
