# Generated by Django 3.0.8 on 2021-02-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210219_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='harga_jual',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
