# Generated by Django 3.0.8 on 2021-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210219_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dana_masuk',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
