# Generated by Django 3.0.8 on 2021-02-21 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210221_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal_pembayaran',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
