# Generated by Django 3.0.8 on 2020-10-11 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='VechileType',
            fields=[
                ('IDJenis', models.IntegerField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(choices=[('big', 'Big'), ('medium', 'Medium'), ('elf', 'Elf'), ('Hiace', 'Sprinter')], max_length=10)),
                ('jumlah_seat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_polisi', models.CharField(max_length=10)),
                ('tanggal_stnk', models.DateField()),
                ('status_stnk', models.CharField(max_length=10)),
                ('tanggal_pembelian', models.DateField()),
                ('harga_beli', models.PositiveIntegerField()),
                ('scan_faktur_beli', models.CharField(max_length=10)),
                ('IDJenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.VechileType')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor')),
            ],
        ),
    ]
