# Generated by Django 3.0.8 on 2020-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_vechile_vechiletype_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alamat_vendor',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nama_vendor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notelp_kantor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notelp_pic',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pic_vendor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vechiletype',
            name='jenis',
            field=models.CharField(choices=[('big', 'Big'), ('medium', 'Medium'), ('elf', 'Elf'), ('hiace', 'Hiace'), ('sprinter', 'Sprinter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
