# Generated by Django 3.0.8 on 2020-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201016_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechile',
            name='photo',
            field=models.ImageField(null=True, upload_to='store/images'),
        ),
    ]
