# Generated by Django 3.0.8 on 2020-11-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201121_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechile',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
