# Generated by Django 3.0.8 on 2020-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201122_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiletype',
            name='IDJenis',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
