# Generated by Django 3.0.8 on 2020-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_vechiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiletype',
            name='merek',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
