# Generated by Django 3.0.8 on 2020-12-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20201205_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vechile',
            name='expires_today',
        ),
    ]
